HW by Valery Myrzin
AufarZakiev/CPP-2019-2020-HW2 pull request #2
Opened 2019-10-28 18:44 UTC by waleramir

2019-10-28 19:20 UTC, waleramir commented
@AufarZakiev checking

2019-10-28 19:24 UTC, AufarZakiev requested changes
Empty review

2019-10-29 06:12 UTC, AufarZakiev requested changes
Реализации функций - хорошие, молодец. С линковкой тоже разобрался, я вижу.
Осталось заинклудить в **main** не сами **.cpp** файлы, а заголовочные файлы **.h**, чтобы все было хорошо

2019-10-29 11:13 UTC, AufarZakiev requested changes
Помните пример с инклудом **.cpp** файлов, что я показывал на паре? Это приводит к повторному инклуду функций в некоторых случаях, на что компилятор ругнется из-за повторого опредления тела функции.
Поэтому **.cpp** файлы мы не инклудим никогда.

Мы создаем для них заголовочные файлы и инклудим их. А тела функций найдет уже линковщик (см. схему с пары)

![photo_2019-10-28_14-47-37](https://user-images.githubusercontent.com/5558521/67762352-4a2b6480-fa56-11e9-844a-d29a2848657f.jpg
)

2019-10-29 11:45 UTC, AufarZakiev approved these changes
Гуд! Если остались вопросы по тому, как работает весь механизм с инклудами и линковкой - пишите

2020-09-28 07:28 UTC, closed without merging